"""
Separated script to enable Gmail Push Notifications (Cloud Watch)
This connects your Gmail Inbox to the Google Cloud Pub/Sub topic created by setup_gcp_infra.sh.

It requires:
1. token.json (generated by setup_auth.py)
2. .env (generated by setup_gcp_infra.sh with PROJECT_ID)

Usage:
    python scripts/enable_cloud_watch.py
"""

import os
import sys
import json

# Add project root to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from google.auth.transport.requests import Request

# Same scopes as setup_auth.py
SCOPES = [
    'https://www.googleapis.com/auth/gmail.readonly',
    'https://www.googleapis.com/auth/gmail.modify',
    'https://www.googleapis.com/auth/spreadsheets'
]

def load_credentials():
    """Loads existing credentials from token.json"""
    root_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    token_path = os.path.join(root_dir, 'token.json')
    
    if not os.path.exists(token_path):
        print("❌ Error: 'token.json' not found.")
        print("   Please run 'python scripts/setup_auth.py' first to authenticate.")
        return None
        
    try:
        creds = Credentials.from_authorized_user_file(token_path, SCOPES)
        return creds
    except Exception as e:
        print(f"❌ Error loading token: {e}")
        return None

def setup_cloud_watch():
    creds = load_credentials()
    if not creds:
        return

    # Check validity
    if not creds.valid:
        if creds.expired and creds.refresh_token:
            print("🔄 Refreshing expired credentials...")
            try:
                creds.refresh(Request())
            except Exception as e:
                print(f"❌ Token refresh failed: {e}")
                print("   Please re-run 'python scripts/setup_auth.py'")
                return
        else:
            print("❌ Credentials invalid. Please re-run 'python scripts/setup_auth.py'")
            return

    # Read config from .env
    env_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), '.env')
    project_id = None
    
    if os.path.exists(env_path):
        with open(env_path, 'r') as f:
            for line in f:
                if line.startswith("PROJECT_ID="):
                    project_id = line.strip().split("=")[1]
    
    if not project_id:
        print("❌ Error: PROJECT_ID not found in .env")
        print("   Did you run './scripts/setup_gcp_infra.sh'?")
        return

    # Read topic from .env if available, else default
    topic_name = "gmail-notifications"
    if os.path.exists(env_path):
        with open(env_path, 'r') as f:
            for line in f:
                if line.startswith("PUBSUB_TOPIC="):
                    topic_name = line.strip().split("=")[1]
    
    full_topic = f"projects/{project_id}/topics/{topic_name}"
    
    print("\n--- 🔔 Gmail Push Notification Setup ---")
    print(f"Target Topic: {full_topic}")
    
    try:
        service = build('gmail', 'v1', credentials=creds)
        request = {
            'labelIds': ['INBOX'],
            'topicName': full_topic
        }
        service.users().watch(userId='me', body=request).execute()
        print(f"✅ Gmail Watch enabled successfully!")
        print(f"   Any new email in Inbox will trigger the Cloud Function via {topic_name}.")
    except Exception as e:
        print(f"❌ Failed to enable Gmail Watch: {e}")
        if "404" in str(e) or "notFound" in str(e):
            print(f"\n💡 Diagnosis: The Pub/Sub topic '{topic_name}' does NOT exist in project '{project_id}'.")
            print("   👉 Solution: Run './scripts/setup_gcp_infra.sh' to create the necessary cloud resources.")
        elif "403" in str(e) or "forbidden" in str(e):
            print("\n💡 Diagnosis: Permission denied.")
            print("   👉 Solution 1: Run './scripts/setup_gcp_infra.sh' again to grant 'gmail-api-push' permissions.")
            print("   👉 Solution 2: Ensure the Gmail API is enabled and your token has the right scopes.")

if __name__ == "__main__":
    setup_cloud_watch()
